# Project Name
name: Gather Workshops

# Jekyll Version
version: 3.1.6

# theme
themecolor: "#F21800"

baseurl: ""
theme_assets: "/theme/assets"
theme_images: "/theme/assets/images"
course_images: "/media/images"

# Markdown Config
markdown: kramdown
exclude: ["node_modules", "Gemfile", "Gruntfile.js", "package.json", "README.md"]

kramdown:
  input: GFM
  enable_coderay: false

# Where things are
source:       .
destination:  ./_site
layouts_dir:  ./theme/_layouts
includes_dir: ./theme/_includes
sass:
    sass_dir: ./theme/_sass

# custom collections
collections:
  assets:
    output: true
  courses:
    output: true
    layout: chapter

